#!/bin/sh
xset b off  # Disable the audible bell.
xrandr --dpi 96  # Set the fonts to the normal DPI.
xrdb -load "$HOME/.Xresources"
if [ -x /usr/local/bin/picom ]
then
    /usr/local/bin/picom -b
fi
if [ -x /usr/local/bin/hsetroot ]
then
    sleep 1
    /usr/local/bin/hsetroot -solid "rgb:10/10/10"
fi
return 0
