#!/usr/bin/env ansible-playbook
---
- name: Setup CLI
  hosts: localhost
  vars:
    gui: false
  tasks:
    - include_role:
        name: arch
      when: ansible_distribution == 'Archlinux'
    - include_role:
        name: debian
      when: ansible_distribution == 'Debian'
    - include_role:
        name: fedora
      when: ansible_distribution == 'Fedora'
    - include_role:
        name: freebsd
      when: ansible_distribution == 'FreeBSD'
    - include_role:
        name: netbsd
      when: ansible_distribution == 'NetBSD'
    - include_role:
        name: ubuntu
      when: ansible_distribution == 'Ubuntu'
    - include_role:
        name: home-cli
