#!/usr/bin/env ansible-playbook
---
- name: Setup GUI
  hosts: localhost
  vars:
    gui: true
  tasks:
    - include_role:
        name: debian
      when: ansible_distribution == 'Debian'
    - include_role:
        name: freebsd
      when: ansible_distribution == 'FreeBSD'
    - include_role:
        name: netbsd
      when: ansible_distribution == 'NetBSD'
    - include_role:
        name: ubuntu
      when: ansible_distribution == 'Ubuntu'
    - include_role:
        name: home-cli
    - include_role:
        name: home-gui
