---
# Copyright 2021 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Disable getty on /dev/console
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ttys
    regexp: ^console\s+
    line: 'console	"/usr/libexec/getty Pc"		vt100	off secure'
- name: Enable getty on /dev/ttyE0
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ttys
    regexp: ^ttyE0\s+
    line: 'ttyE0	"/usr/libexec/getty Pc"		wsvt25	on secure'
