---
- name: Configure pkg to ignore OSABI
  become: true
  lineinfile:
    path: /etc/pkg_install.conf
    regexp: '^CHECK_OSABI='
    line: 'CHECK_OSABI=no'
    create: yes
- name: Install CLI packages
  become: true
  pkgin:
    name: git,gnupg2,mc,mozilla-rootcerts-openssl,nmap,openvpn,pkgin,py37-pip,python37,sqlite3,sudo,tmux,zsh
    state: present
