---
# Copyright 2021 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure pkg to ignore OSABI
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pkg_install.conf
    regexp: '^CHECK_OSABI='
    line: 'CHECK_OSABI=no'
    create: yes
- name: Configure PKG_PATH
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pkg_install.conf
    regexp: '^PKG_PATH='
    line: 'PKG_PATH=http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/{{ ansible_machine }}/{{ ansible_distribution_release }}/All'
    create: yes
- name: Install CLI packages
  become: true
  community.general.pkgin:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - git
      - gnupg2
      - heirloom-doctools
      - mc
      - mozilla-rootcerts-openssl
      - nmap
      - openvpn
      - pkgin
      - py37-pip
      - python37
      - ruby
      - sqlite3
      - sudo
      - zsh
