---
- name: Configure pkg to ignore OSABI
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pkg_install.conf
    regexp: '^CHECK_OSABI='
    line: 'CHECK_OSABI=no'
    create: yes
- name: Configure PKG_PATH
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pkg_install.conf
    regexp: '^PKG_PATH='
    line: 'PKG_PATH=http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/{{ ansible_machine }}/{{ ansible_distribution_release }}/All'
    create: yes
- name: Install CLI packages
  become: true
  community.general.pkgin:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - ansible
      - git
      - gnupg2
      - heirloom-doctools
      - mc
      - mozilla-rootcerts-openssl
      - nmap
      - openvpn
      - pkgin
      - py37-pip
      - python37
      - ruby
      - sqlite3
      - sudo
      - zsh
