---
- name: Enable xdm
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: ^xdm=.*
    line: xdm=YES
- name: Copy dbus service
  become: true
  ansible.builtin.copy:
    src: /usr/pkg/share/examples/rc.d/dbus
    dest: /etc/rc.d/dbus
    remote_src: yes
- name: Enable dbus
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: ^dbus=.*
    line: dbus=YES
