---
- name: Install GUI packages
  become: true
  dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - emacs
      - galculator
      - git-gui
      - liberation-fonts
      - remmina
      - vim-X11
