---
- name: Install CLI packages
  become: true
  dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@c-development"
      - ansible
      - asciidoctor
      - aspell-en
      - bc
      - bind-utils
      - clang
      - git
      - gnupg
      - lldb
      - mc
      - nmap
      - nodejs
      - onedrive
      - openssh-server
      - python3
      - python3-psutil
      - rubygem-asciidoctor-pdf
      - sqlite
      - sudo
      - tlp
      - tmux
      - vim
      - wordgrinder
      - zsh
- name: Enable TLP
  become: true
  systemd:
    name: tlp.service
    enabled: true
    state: started
