---
- name: Create user applications directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory
- name: Create user autostart directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
- name: Create ~/.fvwm directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fvwm"
    state: directory
- name: Create ~/.local/share/fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
