---
- name: Create user applications directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory
- name: Create user autostart directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
- name: Create ~/.fvwm directory
  file:
    path: "{{ ansible_env.HOME}}/.fvwm"
    state: directory
