---
- name: Copy .Xresources
  ansible.builtin.copy:
    src: Xresources
    dest: "{{ ansible_env.HOME }}/.Xresources"
- name: Copy .fonts.conf
  ansible.builtin.copy:
    src: fonts.conf
    dest: "{{ ansible_env.HOME }}/.fonts.conf"
- name: Create stalonetrayrc
  ansible.builtin.copy:
    src: stalonetrayrc
    dest: "{{ ansible_env.HOME }}/.stalonetrayrc"
- name: Create fvwm config file
  ansible.builtin.copy:
    src: fvwmrc
    dest: "{{ ansible_env.HOME }}/.fvwm/config"
- name: Create NetBSD xsession file
  ansible.builtin.copy:
    src: xsession-netbsd
    dest: "{{ ansible_env.HOME }}/.xsession"
  when: ansible_system == "NetBSD"
- name: Create xinitrc symlink
  ansible.builtin.file:
    src: ".xsession"
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    state: link
  when: ansible_system == "NetBSD"
- name: Load ~/.Xresources
  ansible.builtin.copy:
    src: "xrdb.desktop"
    dest: "{{ ansible_env.HOME }}/.config/autostart/xrdb.desktop"
  when: ansible_distribution == "Fedora" or ansible_distribution == "Debian"
- name: Add to-do list launcher
  ansible.builtin.template:
    src: todo.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/todo.desktop"
- name: Copy .xbindkeysrc
  ansible.builtin.copy:
    src: "xbindkeysrc"
    dest: "{{ ansible_env.HOME }}/.xbindkeysrc"
- name: Add custom Chromium launcher
  ansible.builtin.template:
    src: chromium-browser.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/chromium-browser.desktop"
  vars:
    prefix: "{{ '/usr' if ansible_system == 'Linux' else '/usr/pkg' if ansible_system == 'NetBSD' else '/usr/local' }}"
