---
# Copyright 2021 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check for regular profiles.ini
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.mozilla/firefox/profiles.ini"
  register: profile_ini
- name: Copy Firefox preferences to regular Profile0
  ansible.builtin.copy:
    src: user.js
    dest: "{{ ansible_env.HOME }}/.mozilla/firefox/{{ lookup('ini', 'Path section=Profile0 file={{ ansible_env.HOME }}/.mozilla/firefox/profiles.ini') }}/user.js"
  when: profile_ini.stat.exists
- name: Check for Flatpak profiles.ini
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.var/app/org.mozilla.firefox/.mozilla/firefox/profiles.ini"
  register: profile_ini_flatpak
- name: Copy Firefox preferences to Flatpak Profile0
  ansible.builtin.copy:
    src: user.js
    dest: "{{ ansible_env.HOME }}/.var/app/org.mozilla.firefox/.mozilla/firefox/{{ lookup('ini', 'Path section=Profile0 file={{ ansible_env.HOME }}/.var/app/org.mozilla.firefox/.mozilla/firefox/profiles.ini') }}/user.js"
  when: profile_ini_flatpak.stat.exists
- name: Check for MacOS profiles.ini
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Firefox/profiles.ini"
  register: profile_ini_macos
- name: Copy Firefox preferences to regular Profile0
  ansible.builtin.copy:
    src: user.js
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Firefox/{{ lookup('ini', 'Path section=Profile0 file={{ ansible_env.HOME }}/Library/Application Support/Firefox/profiles.ini') }}/user.js"
  when: profile_ini_macos.stat.exists
