---
# Copyright 2021-2023 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install Google signing key
  become: true
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/google.asc
    checksum: sha256:fb8df9740df6a1125fd2983465d830b764b63cd92d5ada8b5bbf75927d6a71ee
- name: Install Google repository
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/google-chrome.list
    regexp: '^deb .* https://dl.google.com/linux/chrome/deb/'
    line: 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main'
    create: yes
    mode: '644'
- name: Install Google Chrome package
  become: true
  ansible.builtin.apt:
    name: 'google-chrome-stable'
    state: present
    force_apt_get: yes
    update_cache: yes
