---
- name: Install CLI packages
  become: true
  apt:
    name: '{{ packages }}'
    state: present
    force_apt_get: yes
  vars:
    packages:
      - apt-file
      - ansible
      - asciidoctor
      - clang
      - clang-format
      - console-data
      - cowsay
      - curl
      - dc
      - dnsutils
      - exfat-fuse
      - exfat-utils
      - figlet
      - git
      - gnupg
      - groff
      - lldb
      - mc
      - nftables
      - nmap
      - openssh-server
      - packagekit
      - python3
      - python3-psutil
      - ruby-asciidoctor-pdf
      - sipcalc
      - sqlite3
      - sshpass
      - sudo
      - tlp
      - tmux
      - vim
      - wordgrinder-ncurses
      - zsh
- name: Load /etc/profile in zsh
  become: true
  lineinfile:
    path: /etc/zsh/zprofile
    line: emulate sh -c 'source /etc/profile'
