---
- name: Install GUI packages
  become: true
  apt:
    name: '{{ packages }}'
    state: present
    force_apt_get: yes
  vars:
    packages:
      - dconf-cli
      - emacs
      - evolution
      - galculator
      - git-gui
      - latexmk
      - libcanberra-gtk-module
      - mpv
      - nextcloud-desktop
      - remmina
      - rxvt-unicode
      - texlive
      - texlive-pictures
      - texlive-science
      - vim-gtk
      - xinput
      - xterm
