---
- name: Install GUI packages
  become: true
  apt:
    name: '{{ packages }}'
    state: present
    force_apt_get: yes
  vars:
    packages:
      - dconf-cli
      - desktop-base
      - emacs
      - evolution
      - galculator
      - git-gui
      - kleopatra
      - mpv
      - nextcloud-desktop
      - redshift-gtk
      - remmina
      - rxvt-unicode
      - task-british-desktop
      - task-kde-desktop
      - vim-gtk
      - xinput
      - xterm
