---
- name: Install GUI packages
  become: true
  apt:
    name: '{{ packages }}'
    state: present
    force_apt_get: yes
  vars:
    packages:
      - dconf-cli
      - desktop-base
      - emacs
      - evolution
      - galculator
      - git-gui
      - gnome-tweaks
      - latexmk
      - mpv
      - nautilus-nextcloud
      - nextcloud-desktop
      - remmina
      - rxvt-unicode
      - task-british-desktop
      - task-gnome-desktop
      - task-print-server
      - texlive
      - texlive-pictures
      - texlive-science
      - vim-gtk
      - xinput
      - xterm
