---
# Copyright 2022 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create /etc/systemd/system.conf.d
  become: true
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: directory
    mode: '0755'
- name: Create /etc/systemd/system.conf.d/DefaultTimeoutStopSec.conf
  become: true
  ansible.builtin.copy:
    src: DefaultTimeoutStopSec.conf
    dest: "/etc/systemd/system.conf.d/DefaultTimeoutStopSec.conf"
  register: system_conf_d
- name: Create /etc/systemd/user.conf.d
  become: true
  ansible.builtin.file:
    path: "/etc/systemd/user.conf.d"
    state: directory
    mode: '0755'
- name: Create /etc/systemd/user.conf.d/DefaultTimeoutStopSec.conf
  become: true
  ansible.builtin.copy:
    src: DefaultTimeoutStopSec.conf
    dest: "/etc/systemd/user.conf.d/DefaultTimeoutStopSec.conf"
  register: user_conf_d
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: system_conf_d.changed == true or user_conf_d.changed == true
