---
# Copyright 2021-2023 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install Microsoft signing key
  become: true
  ansible.builtin.apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
- name: Install vscode repository
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/vscode.list
    regexp: '^deb .* http://packages.microsoft.com/repos/code'
    line: 'deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main'
    create: yes
    mode: '644'
- name: Install Visual Studio Code package
  become: true
  ansible.builtin.apt:
    name: 'code'
    state: present
    force_apt_get: yes
    update_cache: yes
