---
- name: Install FreeBSD core packages
  become: true
  pkgng:
    name: drm-kmod en-freebsd-doc git mate pkg py36-ansible sudo xdm xorg xterm
    state: present
- name: Install FreeBSD additional packages
  become: true
  pkgng:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - dbus
      - emacs
      - firefox-esr
      - fusefs-ntfs
      - galculator
      - git-gui
      - gnu-watch
      - gnupg
      - iosevka
      - mc
      - mpv
      - nextcloudclient
      - nmap
      - openvpn
      - py36-psutil
      - redshift
      - remmina
      - remmina-plugin-rdp
      - rubygem-asciidoctor
      - rxvt-unicode
      - seahorse
      - sqlite3
      - tmux
      - vim
      - xinput
      - zsh
- name: Start DBUS service
  become: true
  service:
    name: dbus
    state: started
    enabled: yes
- name: Enable XDM
  become: true
  lineinfile:
    path: /etc/ttys
    regexp: '^ttyv8	.*'
    line: 'ttyv8	"/usr/local/bin/xdm -nodaemon"	xterm	on  secure'
