---
- name: Install FreeBSD core CLI packages
  become: true
  pkgng:
    name: en-freebsd-doc git pkg py36-ansible sudo
    state: present
- name: Install FreeBSD additional CLI packages
  become: true
  pkgng:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - fusefs-ntfs
      - gnu-watch
      - gnupg
      - mc
      - nmap
      - openvpn
      - py36-psutil
      - rubygem-asciidoctor
      - sqlite3
      - tmux
      - zsh
- name: Disable core dumps
  become: true
  sysctl:
    name: kern.coredump
    value: '0'
    sysctl_set: yes
- name: Use IPv6 temporary addresses (sysctl.conf)
  become: true
  sysctl:
    name: net.inet6.ip6.use_tempaddr
    value: '1'
    sysctl_set: yes
- name: Prefer IPv6 temporary addresses (sysctl.conf)
  become: true
  sysctl:
    name: net.inet6.ip6.prefer_tempaddr
    value: '1'
    sysctl_set: yes
- name: Disable VT bell
  become: true
  sysctl:
    name: kern.vt.enable_bell
    value: '0'
    sysctl_set: yes
- name: Enable IPv6 privacy (rc.conf)
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ipv6_privacy=.*'
    line: 'ipv6_privacy="YES"'
- name: Set wlan0 arguments
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^create_args_wlan0=.*'
    line: 'create_args_wlan0="country GB"'
- name: Enable WPA/DHCP for wlan0
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_wlan0=.*'
    line: 'ifconfig_wlan0="WPA SYNCDHCP"'
- name: Enable IPv6 for wlan0
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_wlan0_ipv6=.*'
    line: 'ifconfig_wlan0_ipv6="inet6 accept_rtadv"'
- name: Enable wheel group to use sudo
  become: true
  lineinfile:
    path: /usr/local/etc/sudoers.d/wheel
    regexp: 'wheel'
    line: '%wheel ALL=(ALL) ALL'
    create: yes
    mode: '0644'
