---
- name: Install FreeBSD core packages
  become: true
  pkgng:
    name: drm-kmod en-freebsd-doc git mate pkg py36-ansible sudo xdm xorg xterm
    state: present
- name: Install FreeBSD additional packages
  become: true
  pkgng:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - emacs
      - firefox-esr
      - fusefs-ntfs
      - galculator
      - git-gui
      - gnu-watch
      - gnupg
      - iosevka
      - mc
      - mpv
      - nextcloudclient
      - nmap
      - openvpn
      - redshift
      - remmina
      - remmina-plugin-rdp
      - rubygem-asciidoctor
      - rxvt-unicode
      - seahorse
      - sqlite3
      - tmux
      - vim
      - xinput
      - zsh
