---
# Copyright 2021 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set $HOME permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}"
    state: directory
    mode: '0700'
- name: Create $HOME/.local
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local"
    state: directory
    mode: '0700'
- name: Create $HOME/.local/bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0700'
- name: Create $XDG_CONFIG_HOME
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}"
    state: directory
    mode: '0700'
- name: Create $XDG_CONFIG_HOME/systemd/user
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/systemd/user"
    state: directory
- name: Create $HOME/.ssh
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
- name: Create $HOME/.ssh/config.d
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/config.d"
    state: directory
    mode: '0700'
- name: Create $XDG_CONFIG_HOME/git
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/git"
    state: directory
- name: Create $XDG_CONFIG_HOME/mc
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/mc"
    state: directory
- name: Create $XDG_CONFIG_HOME/powershell
  ansible.builtin.file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/powershell"
    state: directory
