---
- name: Copy .gemrc
  copy:
    src: gemrc
    dest: "{{ ansible_env.HOME }}/.gemrc"
- name: Copy .gitconfig
  copy:
    src: gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
- name: Copy .hushlogin
  copy:
    src: hushlogin
    dest: "{{ ansible_env.HOME }}/.hushlogin"
- name: Copy .inputrc
  copy:
    src: inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"
- name: Copy .tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: Copy openpgp.asc
  copy:
    src: openpgp.asc
    dest: "{{ ansible_env.HOME }}/.config/openpgp.asc"
