---
# Copyright 2021-2023 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create $HOME/.gemrc
  ansible.builtin.copy:
    src: gemrc
    dest: "{{ ansible_env.HOME }}/.gemrc"
- name: Create $HOME/.tmux.conf
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: Create $XDG_CONFIG_HOME/openpgp.asc
  ansible.builtin.copy:
    src: openpgp.asc
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/openpgp.asc"
- name: Create $HOME/.dput.cf
  ansible.builtin.copy:
    src: dput.cf
    dest: "{{ ansible_env.HOME }}/.dput.cf"
- name: Create $HOME/.mailcap
  ansible.builtin.copy:
    src: mailcap
    dest: "{{ ansible_env.HOME }}/.mailcap"
- name: Create $XDG_CONFIG_HOME/git/config
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/git/config"
- name: Create $HOME/.quiltrc-dpkg
  ansible.builtin.copy:
    src: quiltrc-dpkg
    dest: "{{ ansible_env.HOME }}/.quiltrc-dpkg"
- name: Create $XDG_CONFIG_HOME/editorconfig
  ansible.builtin.copy:
    src: editorconfig
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/editorconfig"
- name: Create $HOME/.clang-format
  ansible.builtin.copy:
    src: clang-format
    dest: "{{ ansible_env.HOME }}/.clang-format"
- name: Create $HOME/.editorconfig
  ansible.builtin.copy:
    src: editorconfig
    dest: "{{ ansible_env.HOME }}/.editorconfig"
- name: Create $HOME/.local/bin/docutils-setup
  ansible.builtin.copy:
    src: docutils-setup.sh
    dest: "{{ ansible_env.HOME }}/.local/bin/docutils-setup"
    mode: '0755'
- name: Create $XDG_CONFIG_HOME/mc/ini
  ansible.builtin.copy:
    src: mc.ini
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/mc/ini"
- name: Create $XDG_CONFIG_HOME/mc/panels.ini
  ansible.builtin.copy:
    src: mc.panels.ini
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/mc/panels.ini"
- name: Create $XDG_CONFIG_HOME/powershell/Microsoft.PowerShell_profile.ps1
  ansible.builtin.copy:
    src: Microsoft.PowerShell_profile.ps1
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/powershell/Microsoft.PowerShell_profile.ps1"
- name: Create $HOME/.local/bin/virtinst
  ansible.builtin.copy:
    src: virtinst.sh
    dest: "{{ ansible_env.HOME }}/.local/bin/virtinst"
    mode: '0755'
- name: Create $HOME/.local/bin/virtxp
  ansible.builtin.copy:
    src: virtxp.sh
    dest: "{{ ansible_env.HOME }}/.local/bin/virtxp"
    mode: '0755'
- name: Create $XDG_CONFIG_HOME/user-dirs.dirs
  ansible.builtin.copy:
    src: user-dirs.dirs
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/user-dirs.dirs"
- name: Create $XDG_CONFIG_HOME/containers/storage.conf
  ansible.builtin.copy:
    src: storage.conf
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/containers/storage.conf"
- name: Create $XDG_DATA_HOME/azerty-afnor.txt
  ansible.builtin.copy:
    src: azerty-afnor.txt
    dest: "{{ ansible_env.XDG_DATA_HOME }}/azerty-afnor.txt"
# Get the latest version from <https://dotnet.microsoft.com/en-us/download/dotnet/scripts>
- name: Create $HOME/.local/bin/dotnet-install.sh
  ansible.builtin.copy:
    src: dotnet-install.sh
    dest: "{{ ansible_env.HOME }}/.local/bin/dotnet-install.sh"
    mode: '0755'
