---
- name: Copy .gemrc
  copy:
    src: gemrc
    dest: "{{ ansible_env.HOME }}/.gemrc"
- name: Remove .hushlogin
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: absent
- name: Copy .tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: Copy openpgp.asc
  copy:
    src: openpgp.asc
    dest: "{{ ansible_env.HOME }}/.config/openpgp.asc"
- name: Copy .dput.cf
  copy:
    src: dput.cf
    dest: "{{ ansible_env.HOME }}/.dput.cf"
- name: Copy .mailcap
  copy:
    src: mailcap
    dest: "{{ ansible_env.HOME }}/.mailcap"
