---
- name: Copy .bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
- name: Copy .bash_profile
  ansible.builtin.copy:
    src: bash_profile
    dest: "{{ ansible_env.HOME }}/.bash_profile"
- name: Copy .profile
  ansible.builtin.copy:
    src: profile
    dest: "{{ ansible_env.HOME }}/.profile"
- name: Copy .shrc
  ansible.builtin.copy:
    src: shrc
    dest: "{{ ansible_env.HOME }}/.shrc"
- name: Copy .zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
