#!/bin/sh
. "$HOME/.profile"
xset b off  # Disable the audible bell.
xrandr --dpi 96  # Set the fonts to the normal DPI.
xrdb -load "$HOME/.Xresources"
if [ -x /usr/local/bin/picom ]
then
    /usr/local/bin/picom -b
fi
exec icewm-session
