#!/bin/sh
. $HOME/.profile
xrdb -load $HOME/.Xresources
if test -r $HOME/.Xresources.local
then
    xrdb -override $HOME/.Xresources.local
fi
xsetroot -solid '#101010'
backlight 10
mixer vol.mute=1
xkbcomp -w0 -I"${XDG_CONFIG_HOME:-$HOME/.config}/xkb" -R"${XDG_CONFIG_HOME:-$HOME/.config}/xkb" keymap/acp $DISPLAY

if test -x "$(command -v onedrive)"
then
    pgrep -U $(id -u) onedrive || nice onedrive --monitor &
fi

exec /usr/local/bin/icewm-session
