#!/bin/bash
export ACP_BASH_PROFILE=1

if [ -r /etc/profile ]
then
    . /etc/profile
fi

export BASH_ENV="$HOME/.bashrc"
export BLOCKSIZE=K
export EDITOR=vi
export LANG=C
export PAGER=less

if [ -r "$HOME/.bash_profile.$(hostname -s)" ]
then
    . "$HOME/.bash_profile.$(hostname -s)"
fi

if [ -z "$ACP_BASHRC" ] || [ -n "$SSH_TTY" ]
then
    . "$HOME/.bashrc"
fi
