#!/bin/bash
if [ -r /etc/profile ]
then
	. /etc/profile
fi

export BASH_ENV="$HOME/.bashrc"

export _acp_ignore_shrc=1
if [ -r "$HOME/.profile" ]
then
	. "$HOME/.profile"
fi
unset _acp_ignore_shrc

if [ -r "$HOME/.bashrc" ]
then
	. "$HOME/.bashrc"
fi
