#!/bin/sh
export ANSIBLE_NOCOWS=1
export BLOCKSIZE=K
export EDITOR=vi
export ENV="$HOME/.shrc"
export HISTCONTROL=ignorespace:ignoredups
export LANG=C
export PAGER=less
export PAPERSIZE=a4
export POWERSHELL_TELEMETRY_OPTOUT=1
export PS1="${PS1:-\$\ }"
export PYTHONWARNINGS=ignore::UserWarning

# Set up XDG variables. See:
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/etc/xdg}
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/.runtime-$(id -un)}"

# Locale and language.
## Clear the existing locale settings and set options I always want.
export TZ=Europe/London  # Can override this elsewhere if needed.
if [ -r "$XDG_CONFIG_HOME/locale.conf" ]
then
	. "$XDG_CONFIG_HOME/locale.conf"
fi

if [ "${XDG_CURRENT_DESKTOP:-unknown}" = GNOME ]
then
	export QT_FONT_DPI=72
fi

# Desktop files (used by desktop environments within both X11 and Wayland) are
# looked for in XDG_DATA_DIRS; make sure it includes the relevant directory for
# snappy applications' desktop files.
_snap_xdg_path=/var/lib/snapd/desktop
if [ -x /usr/lib/snapd/snapd ] && [ -n "${XDG_DATA_DIRS##*${_snap_xdg_path}}" ] && [ -n "${XDG_DATA_DIRS##*${_snap_xdg_path}:*}" ]
then
	XDG_DATA_DIRS="${XDG_DATA_DIRS}:${_snap_xdg_path}"
fi
unset _snap_xdg_path

if [ -r "$HOME/.profile.$(hostname -s)" ]
then
	. "$HOME/.profile.$(hostname -s)"
fi
