#!/bin/sh
if [ -r "$HOME/.profile" ]
then
    . "$HOME/.profile"
fi

case "$-" in
*i*)
    # Shell is interactive.
    if [ -r /etc/profile.d/bash_completion.sh ]
    then
        . /etc/profile.d/bash_completion.sh
    fi
    if [ -z "$ZSH_VERSION" ]
    then
        set -o emacs
    fi
    usermotd
    ;;
*)
    # Shell is not interactive.
    return 1
    ;;
esac
