#!/bin/zsh
case "$-" in
*i*)
	echo "[ Reading \"$HOME/.zshrc\" ]"
	;;
*)
	# Shell is not interactive.
	return 1
	;;
esac

if [ -f /etc/zshrc ]
then
	. /etc/zshrc
fi

autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end
bindkey "^[OA" history-beginning-search-backward-end
bindkey "^[OB" history-beginning-search-forward-end

export PS1="%B%n@%m%#%b "

if [ -e "$HOME/.shrc" ]
then
	emulate sh -c '. "$HOME/.shrc"'
fi
