---
- name: Create user bin directory
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
- name: Create user opt directory
  file:
    path: "{{ ansible_env.HOME }}/opt"
    state: directory
- name: Create systemd user directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
- name: Create ~/.ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
- name: Create ~/.config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0700'
