---
- name: Create user bin directory
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
- name: Create user opt directory
  file:
    path: "{{ ansible_env.HOME }}/opt"
    state: directory
- name: Create systemd user directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
- name: Create user applications directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory
- name: Create user autostart directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
- name: Create ~/.ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
