---
- name: Install GUI packages
  become: true
  apt:
    name: '{{ packages }}'
    state: present
    force_apt_get: yes
  vars:
    packages:
      - emacs
      - galculator
      - git-gui
      - remmina
      - vim-gtk3
