---
- name: Upgrade all packages
  become: true
  pacman:
    upgrade: yes
- name: Install CLI packages
  become: true
  pacman:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - ansible
      - aspell-en
      - arch-wiki-docs
      - asciidoctor
      - bc
      - bind-tools
      - clang
      - git
      - gnupg
      - lldb
      - man-db
      - mc
      - nmap
      - openssh
      - python
      - python-psutil
      - sudo
      - tlp
      - tmux
      - zsh
- name: Enable TLP
  become: true
  systemd:
    name: tlp.service
    enabled: true
    state: started
