---
- name: Upgrade all packages
  become: true
  community.general.pacman:
    upgrade: yes
- name: Install CLI packages
  become: true
  community.general.pacman:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - ansible
      - aspell-en
      - arch-wiki-docs
      - asciidoctor
      - base-devel
      - bc
      - bind-tools
      - bridge-utils
      - clang
      - cups
      - dnsmasq
      - ebtables
      - git
      - gnupg
      - lldb
      - man-db
      - mc
      - nmap
      - openbsd-netcat
      - openssh
      - python
      - python-psutil
      - sudo
      - tlp
      - tmux
      - zsh
- name: Enable TLP
  become: true
  ansible.builtin.systemd:
    name: tlp.service
    enabled: true
    state: started
