---
- name: Install Ubuntu GUI packages
  become: true
  apt:
    name: '{{ packages }}'
    state: present
    force_apt_get: yes
  vars:
    packages:
      - caja-open-terminal
      - dconf-cli
      - emacs
      - evolution
      - galculator
      - git-gui
      - mpv
      - nextcloud-desktop
      - redshift-gtk
      - remmina
      - rxvt-unicode
      - seahorse
      - vim-gtk
      - xinput
      - xterm
