---
# Copyright 2021-2023 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Enabling these legacy ciphers is required to use MSCHAPv2 for wireless
# networks. The computer will need to be restarted for this change to take
# effect.

- name: Enable legacy_sect section
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pki/tls/openssl.cnf
    regexp: '^#*\[legacy_sect\]'
    line: '[legacy_sect]'
- name: legacy = legacy_sect
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pki/tls/openssl.cnf
    regexp: '^#*legacy = legacy_sect'
    line: 'legacy = legacy_sect'
- name: activate legacy_sect
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pki/tls/openssl.cnf
    regexp: '^#*activate = 1'
    line: 'activate = 1'
