---
- name: Install GUI packages
  become: true
  ansible.builtin.dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - emacs
      - git-gui
      - liberation-fonts
      - vim-X11
