---
- name: Install CentOS Ansible repo
  become: true
  dnf:
    name: centos-release-ansible-29
    state: present
  when: ansible_distribution == 'CentOS'
- name: Install EPEL
  become: true
  dnf:
    name: epel-release
    state: present
- name: Install CLI packages
  become: true
  dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@development"
      - ansible
      - aspell-en
      - bc
      - bind-utils
      - clang
      - git
      - gnupg2
      - lldb
      - mc
      - nmap
      - nodejs
      - openssh-server
      - python38
      - python38-psutil
      - sqlite
      - sudo
      - tmux
      - vim-enhanced
      - zsh
