---
# Copyright 2021 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check for CentOS-Stream-PowerTools.repo file
  ansible.builtin.stat:
    path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
  register: pt
- name: Enable CentOS Stream PowerTools repository
  become: true
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
    create: false
    regexp: ^enabled=
    line: enabled=1
  when: ansible_distribution == 'CentOS' and pt.stat.exists
- name: Install CLI packages
  become: true
  ansible.builtin.dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@development"
      - bc
      - bind-utils
      - clang
      - dnf-automatic
      - git
      - gnupg2
      - lldb
      - mc
      - nmap
      - openssh-server
      - sqlite
      - sudo
      - tmux
      - vim-enhanced
- name: Install CLI packages (EL 8)
  become: true
  ansible.builtin.dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@container-tools"
      - aspell-en
      - python38
      - python38-psutil
  when: ansible_distribution_major_version == 8
