---
- name: Check for CentOS-Stream-PowerTools.repo file
  ansible.builtin.stat:
    path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
  register: pt
- name: Enable CentOS Stream PowerTools repository
  become: true
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
    create: false
    regexp: ^enabled=
    line: enabled=1
  when: ansible_distribution == 'CentOS' and pt.stat.exists
- name: Install CLI packages
  become: true
  ansible.builtin.dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@container-tools"
      - "@development"
      - aspell-en
      - bc
      - bind-utils
      - clang
      - git
      - gnupg2
      - lldb
      - mc
      - nmap
      - nodejs
      - openssh-server
      - python38
      - python38-psutil
      - sqlite
      - sudo
      - tmux
      - vim-enhanced
      - zsh
