---
# Copyright 2021 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install CLI packages (EL 8)
  become: true
  ansible.builtin.dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@container-tools"
      - "@development"
      - aspell-en
      - bc
      - bind-utils
      - clang
      - dnf-automatic
      - git
      - gnupg2
      - mc
      - nmap
      - openssh-server
      - podman
      - python38
      - python38-psutil
      - sqlite
      - sudo
      - tmux
      - toolbox
      - vim-enhanced
  when: ansible_distribution_major_version == '8'
- name: Install CLI packages (EL 9)
  become: true
  ansible.builtin.dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@development"
      - bc
      - bind-utils
      - clang
      - dnf-automatic
      - git
      - gnupg2
      - mc
      - nmap
      - openssh-server
      - podman
      - sqlite
      - sudo
      - tmux
      - toolbox
      - vim-enhanced
      - wireguard-tools
      - zram-generator
  when: ansible_distribution_major_version == '9'
