---
- name: Install CLI packages
  become: true
  dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - "@container-tools"
      - "@development"
      - aspell-en
      - bc
      - bind-utils
      - clang
      - git
      - gnupg2
      - lldb
      - mc
      - nmap
      - nodejs
      - openssh-server
      - python38
      - python38-psutil
      - sqlite
      - sudo
      - tmux
      - vim-enhanced
      - zsh
