---
- name: Install core CLI packages
  become: true
  pkgng:
    name: drm-kmod,en-freebsd-doc,git,pkg,py37-ansible,sudo
    state: present
- name: Install additional CLI packages
  become: true
  pkgng:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - fusefs-ntfs
      - gnu-watch
      - gnupg
      - mc
      - nmap
      - openvpn
      - py37-psutil
      - rubygem-asciidoctor
      - sqlite3
      - tmux
      - zsh
- name: Install asciidoctor-pdf Ruby gem
  become: true
  gem:
    name: asciidoctor-pdf
    state: present
    pre_release: yes
    user_install: no
