---
- name: Install core GUI packages
  become: true
  pkgng:
    name: drm-kmod,xdm,xorg,xterm
    state: present
- name: Install additional GUI packages
  become: true
  pkgng:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - dbus
      - emacs
      - en_GB-libreoffice
      - firefox-esr
      - galculator
      - git-gui
      - iosevka
      - kde5
      - liberation-fonts-ttf
      - libreoffice
      - mpv
      - nextcloudclient
      - redshift
      - remmina
      - remmina-plugin-rdp
      - rxvt-unicode
      - sddm
      - vim
      - xinput
