---
# Copyright 2022 Anthony Perkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install QEMU packages
  become: true
  community.general.pkgng:
    # utouch-kmod and xf86-input-evdev are needed for mouse in QEMU/KVM.
    name: utouch-kmod,xf86-input-evdev
    state: present
- name: Set xorg screen
  become: true
  ansible.builtin.copy:
    src: screen-qemu.conf
    dest: /usr/local/etc/X11/xorg.conf.d/screen-qemu.conf
- name: Enable utouch module
  become: true
  ansible.builtin.lineinfile:
    path: /boot/loader.conf.d/utouch.conf
    regexp: '^utouch_load=.*'
    line: 'utouch_load="YES"'
