---
- name: Enable IPv6 privacy
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ipv6_privacy=.*'
    line: 'ipv6_privacy="YES"'
- name: Set wlan0 arguments
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^create_args_wlan0=.*'
    line: 'create_args_wlan0="country GB"'
- name: Enable WPA/DHCP for wlan0
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_wlan0=.*'
    line: 'ifconfig_wlan0="WPA SYNCDHCP"'
- name: Enable IPv6 for wlan0
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_wlan0_ipv6=.*'
    line: 'ifconfig_wlan0_ipv6="inet6 accept_rtadv"'
- name: Enable SDDM
  become: true
  lineinfile:
    path: /etc/rc.conf
    regexp: '^sddm_enable=.*'
    line: 'sddm_enable="YES"'
