---
- name: Start DBUS service
  become: true
  service:
    name: dbus
    state: started
    enabled: yes
- name: Enable XDM
  become: true
  lineinfile:
    path: /etc/ttys
    regexp: '^ttyv8\s.*'
    line: 'ttyv8	"/usr/local/bin/xdm -nodaemon"	xterm	on  secure'
- name: Set xorg keyboard layout
  become: true
  copy:
    src: keyboard-gb.conf
    dest: /usr/local/etc/X11/xorg.conf.d/keyboard-gb.conf
